config/routes.rb
Rails.application.routes.draw do
  resources :missions
  root "missions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user

  enum priority: [ :urgent, :common, :low ]
  enum category: [ :company, :home ]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :missions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :find_mission, only: [:edit, :update, :destroy]

  def index
    #之後會用分頁處理，目前先用 all 跑出全部資料
    @missions = Mission.all
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(mission_params)
    #因為還沒建後台，先建一個 user 把 mission 都丟給他
    @mission.user = User.first
    if @mission.save
      redirect_to root_path, notice: "新增任務成功！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @mission.update(mission_params)
      redirect_to root_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    if @mission.destroy
      redirect_to root_path, notice: "刪除成功"
    else
      redirect_to root_path, notice: "刪除失敗"
    end
  end


  private
  def find_mission
    @mission = Mission.find_by(id: params[:id])
  end
  def mission_params
    params.require(:mission).permit(:title, :priority, :category, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
  def priority_selection
    [["緊急", 'urgent'], ["普通", "common"], ["沒很重要", "low"]]
  end

  def category_selection
    [["公事", "company"], ["家事", "home"]]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MissionControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/missions/_mission_form.html.erb
<%= form_for mission do |form| %>
  <div>
    <%= form.label :title, "任務名" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :priority, "優先度" %>
    <%= form.select :priority, priority_selection %>
  </div>
  <div>
    <%= form.label :category, "種類" %>
    <%= form.select :category, category_selection %>
  </div>
  <div>
    <%= form.label :start_time, "起始時間" %>
    <%= form.date_select :start_time %>
    <%= form.time_select :start_time, :ignore_date => true %>
  </div>
  <%= form.submit "送出", data: { disable_with: false } %>
<% end %>

app/views/missions/edit.html.erb
<h1>編輯任務</h1>

<%= render "mission_form", mission: @mission %>

app/views/missions/index.html.erb
<h1>任務列表</h1>

<%= link_to "新增任務", new_mission_path %>

<table>
  <thead>
    <tr>
      <td>任務名</td>
      <td>狀態</td>
      <td>起始時間</td>
      <td>結束時間</td>
      <td>優先度</td>
      <td>種類</td>
      <td>動作</td>
    </tr>
  </thead>
  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.title %> </td>
        <td> <%= mission.status %> </td>
        <td> <%= mission.start_time %> </td>
        <td> <%= mission.end_time %> </td>
        <td> <%= mission.priority %> </td>
        <td> <%= mission.category %> </td>
        <td>
          <%= link_to "編輯", edit_mission_path(id: mission.id) %> 
          <%= link_to "刪除", mission_path(id: mission.id), method: "delete", data: { confirm: "確定要刪除嗎?" } %> 
        </td>
      </tr>
    <% end %>
  </tbody>



</table>

app/views/missions/new.html.erb
<h1>新增任務</h1>

<%= render "mission_form", mission: @mission %>